"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-=x&1okkhilg6cebag7c=zu17wqr(b8u$v=l$xpu^j9%#9rmyxf'

DEBUG = False
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'  
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7  # 1 week
 # allow cross-site cookies
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_SAMESITE = 'None'
CSRF_USE_SESSIONS = True
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

ALLOWED_HOSTS = ['*']



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'myapp',
    'crispy_forms',
    'crispy_bootstrap5',
    'cloudinary',
    'rest_framework',
    'corsheaders'
]
cloudinary.config(
    cloud_name = 'dj9mtneqk',
    api_key = '665738545262792',
    api_secret = 'Ve0AuYDPPMeFXCRKlX1_WHTpUvA'
)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dj9mtneqk',
    'API_KEY': '665738545262792',
    'API_SECRET': 'Ve0AuYDPPMeFXCRKlX1_WHTpUvA',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}



DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'


CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     'whitenoise.middleware.WhiteNoiseMiddleware',
]
CORS_ALLOW_CREDENTIALS = True  
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", 
    "http://localhost:5174",
    "https://hr-frontend-nbkexoywm-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-kaiyperuc-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-b6kkgdpwv-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-bm82txnrl-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-aum6g52u8-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-c5x41m696-lisha183s-projects.vercel.app"
]
# CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173", 
    "http://127.0.0.1:8000",
    "http://localhost:5174",
    "https://hr-frontend-vymh-kaiyperuc-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-b6kkgdpwv-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-bm82txnrl-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-aum6g52u8-lisha183s-projects.vercel.app",
    "https://hr-frontend-vymh-c5x41m696-lisha183s-projects.vercel.app"

]
CORS_ALLOW_HEADERS = [
    'content-type',
    'x-csrftoken',
    'authorization',
    'accept',
    'origin',
    'user-agent',
    'accept-encoding',
    'accept-language',
    'dnt',
    'cache-control',
    'x-requested-with',
]

CORS_EXPOSE_HEADERS = [
    'Content-Type',
    'X-CSRFToken',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.parse("postgresql://hr_ppx1_user:0ZgbhSucRI4NX138ZumPANaSvJs9hxuj@dpg-d1mp4824d50c738kqf3g-a.oregon-postgres.render.com/hr_ppx1")
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'hr_db',
#         'USER': 'alicia',
#         'PASSWORD': '123456',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'myapp.CustomUser'
MEDIA_URL = '/media/' 


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = 'sandbox.smtp.mailtrap.io' 
EMAIL_PORT = 587                 
EMAIL_USE_TLS = True              
EMAIL_HOST_USER = '15216b6f087242'
EMAIL_HOST_PASSWORD = '51cfdda9f2ae7f'

DEFAULT_FROM_EMAIL = 'info@myhrportal.local'
SERVER_EMAIL = DEFAULT_FROM_EMAIL 
BASE_URL = 'http://localhost:5173'

