# Generated by Django 5.2.3 on 2025-06-23 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_number', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')], help_text='The quarter number for this assessment (1-4).')),
                ('year', models.IntegerField(help_text='The year for this assessment (e.g., 2025).')),
                ('employee_rating', models.IntegerField(choices=[(1, '1 - Needs Improvement'), (2, '2 - Developing'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Outstanding')], help_text='Employee’s self-rating for the quarter.')),
                ('employee_comments', models.TextField(help_text='Employee’s comments on their performance for the quarter.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the employee submitted the self-assessment.')),
                ('status', models.CharField(choices=[('Pending HR Review', 'Pending HR Review'), ('Completed', 'Completed')], default='Pending HR Review', help_text='Current status of the self-assessment review process.', max_length=50)),
                ('hr_rating', models.IntegerField(blank=True, choices=[(1, '1 - Needs Improvement'), (2, '2 - Developing'), (3, '3 - Meets Expectations'), (4, '4 - Exceeds Expectations'), (5, '5 - Outstanding')], help_text='HR’s rating for the employee’s performance.', null=True)),
                ('hr_feedback', models.TextField(blank=True, help_text='HR’s feedback on the employee’s performance.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when the HR review was completed.', null=True)),
                ('employee', models.ForeignKey(help_text='The employee who submitted this self-assessment.', on_delete=django.db.models.deletion.CASCADE, related_name='self_assessments', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The HR user who reviewed this assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_reviewed_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Self-Assessment & HR Review',
                'verbose_name_plural': 'Self-Assessments & HR Reviews',
                'ordering': ['-year', '-quarter_number', 'employee__username'],
                'unique_together': {('employee', 'quarter_number', 'year')},
            },
        ),
    ]
