# Generated by Django 5.2.3 on 2025-06-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_selfassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfassessment',
            name='employee_comments',
        ),
        migrations.RemoveField(
            model_name='selfassessment',
            name='employee_rating',
        ),
        migrations.AddField(
            model_name='selfassessment',
            name='employee_answers',
            field=models.JSONField(default=list, help_text='JSON array of employee self-assessment questions, ratings, and comments.'),
        ),
    ]
