# Generated by Django 5.2.3 on 2025-07-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_meetingslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basic salary of the employee.', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='selfassessment',
            name='employee_answers',
            field=models.JSONField(default=list, help_text='JSON array of employee self-assessment answers. Each object must have question_id and rating.'),
        ),
    ]
