# Generated by Django 5.2.3 on 2025-07-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_payroll_basic_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Allowances for the period.', max_digits=10),
        ),
    ]
