# Generated by Django 5.2.3 on 2025-07-01 10:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_payroll_allowances'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='bonuses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonuses for the pay period.', max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='tax_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Tax deduction for the period.', max_digits=10),
        ),
    ]
