# Generated by Django 5.2.3 on 2025-07-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_payroll_bonuses_payroll_tax_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='social_security_deduction',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Social security deduction for the period.', max_digits=10),
        ),
    ]
