# Generated by Django 5.2.3 on 2025-07-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_payroll_social_security_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='other_deductions',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Temporary field to be removed.', max_digits=10),
        ),
    ]
