# Generated by Django 5.2.3 on 2025-07-01 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_payroll_other_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='other_deductions',
        ),
    ]
